version: '3'

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["python", "app.py"]

  streamlit:
    build:
      context: .
    ports:
      - "8001:8001"
    command: ["streamlit", "run", "--server.address", "0.0.0.0", "stream.py"]